import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME_BIN, args: ['--no-sandbox', '--disable-dev-shm-usage'] })
const p = await b.newPage({ viewport: { width: 1280, height: 820 }, deviceScaleFactor: 2 })
await p.goto('http://localhost:4173/', { waitUntil: 'load' })
await p.waitForTimeout(2500)
await p.click('input[aria-label="Suche im Werk"]')
await p.type('input[aria-label="Suche im Werk"]', 'Daniel', { delay: 60 })
await p.waitForTimeout(700)
await p.screenshot({ path: '/tmp/search.png' })
await b.close()
console.log('ok')
