import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME_BIN, args:['--no-sandbox','--disable-dev-shm-usage'] })
const p = await b.newPage({ viewport:{width:1280,height:900}, deviceScaleFactor:2 })
await p.goto('http://localhost:4173/#/modul/muhammad/siegel/daniel', { waitUntil:'load' })
await p.waitForTimeout(2200)
await p.evaluate(()=>document.querySelector('.beleg-card--quran')?.scrollIntoView({block:'center'}))
await p.waitForTimeout(400)
await p.click('.beleg-card--quran'); await p.waitForTimeout(900)
await p.screenshot({ path:'/tmp/q-modal.png' })
await p.keyboard.press('Escape'); await p.waitForTimeout(400)
await p.evaluate(()=>document.querySelector('.exhibits-grid')?.scrollIntoView({block:'start'}))
await p.waitForTimeout(700)
await p.screenshot({ path:'/tmp/q-exhibits.png' })
await b.close(); console.log('ok')
